name: CRM CI/CD Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    backend:
        name: Backend Tests
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./api
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Node.js Setup
              uses: actions/setup-node@v3
              with:
                node-version: 20

            - name: Install Dependencies
              run: npm install

            # - name: Run backend tests
            #   run: npm test

    frontend:
        name: Frontend Tests & Build
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./frontend
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                node-version: 20

            - name: Install Dependencies
              run: npm install

            # - name: Run frontend tests
            #   run: npm test

            - name: Build Next.js frontend
              run: npm run build


    vercel-deploy:
        name: Deploy to Vercel
        runs-on: ubuntu-latest
        needs: frontend
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Install Vercel CLI
              run: npm install -g vercel

            - name: Deploy
              env:
                VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
              run: vercel --prod --confirm